# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-02 08:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('subscription', models.IntegerField(choices=[(1, 'Free User'), (2, 'Premium User')], default=1)),
                ('expired_date', models.DateTimeField(auto_now_add=True)),
                ('token', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'db_table': 'user_profile',
            },
        ),
    ]
