# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-08 02:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_auto_20160607_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='agent_ping_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016, 6, 8, 2, 42, 13, 873481, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='time_avg',
            field=models.FloatField(blank=True, default=999),
        ),
    ]
