# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-02 08:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('address', models.URLField(max_length=255)),
                ('vhost', models.CharField(blank=True, default='default', max_length=255)),
            ],
            options={
                'db_table': 'ips',
            },
        ),
    ]
