# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-02 08:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('ip', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ip',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.UserProfile'),
        ),
        migrations.AlterUniqueTogether(
            name='ip',
            unique_together=set([('user_profile', 'address', 'vhost')]),
        ),
    ]
